AddModelVirtualAttributeCheck: { }
# NOTE: デグレ回避のため一旦エスケープ
AlwaysAddDbIndexCheck:
  ignored_files:
    - "db/schema.rb"
#CheckSaveReturnValueCheck: { }
#CheckDestroyReturnValueCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
#HashSyntaxCheck: { }
IsolateSeedDataCheck: { }
KeepFindersOnTheirOwnModelCheck: { }
LawOfDemeterCheck:
  ignored_files:
    - "app/views/admin/orders/_report.html.erb"
#LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck:
 ignored_files:
  - "app/views/partners/orders/show.html.erb"
MoveFinderToNamedScopeCheck: { }
# NOTE: デグレ回避のため一旦エスケープ
MoveModelLogicIntoModelCheck:
  use_count: 6
  ignored_files:
    - "app/controllers/customers/orders_controller.rb"
    - "app/controllers/home_controller.rb"
    - "app/controllers/customers/reports_controller.rb"
    - "app/controllers/customers/chats_controller.rb"
    - "app/controllers/partners/reports_controller.rb"
    - "app/controllers/partners/chats_controller.rb"
    - "app/controllers/customers/recreation_files_controller.rb"
    - "app/controllers/application_controller.rb"
    - "app/controllers/partners/orders_controller.rb"
    - "app/controllers/api_customer/recreation_plan_estimates_controller.rb"
NeedlessDeepNestingCheck: { nested_count: 2 }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
NotUseTimeAgoInWordsCheck: { }
OveruseRouteCustomizationsCheck:
  ignored_files:
    - "config/routes.rb"
    - "config/routes/*"
ProtectMassAssignmentCheck: { }
RemoveEmptyHelpersCheck:
  ignored_files:
    - "app/helpers/home_helper.rb"
#RemoveTabCheck: { }
RemoveTrailingWhitespaceCheck: { }
RemoveUnusedMethodsInControllersCheck: {
  except_methods: [
    'ApplicationController#authenticate_admin!',
    'CustomDevise::RegistrationsController#update_resource',
    'CustomDevise::RegistrationsController#after_update_path_for',
    'CustomDevise::RegistrationsController#configure_account_update_params',
    'CustomDevise::RegistrationsController#after_inactive_sign_up_path_for',
    'CustomDevise::SessionsController#after_sign_in_path_for',
    'CustomDevise::RegistrationsController#configure_sign_up_params',
    'HomeController#pick_recreation_by_id',
    'Partners::ProfilesController#set_profile',
    'Partners::ProfilesController#params_create',
    'Partners::RegistrationsController#redirect_if_partner_logged_in',
    'Partners::RegistrationsController#store_location'
  ]
}
RemoveUnusedMethodsInHelpersCheck: { except_methods: [] }
# NOTE: デグレ回避のため一旦エスケープ
RemoveUnusedMethodsInModelsCheck: {
  except_methods: [
    'User#after_confirmation',
    'Company#without_channel_subscribe'
  ]
}
# NOTE: デグレ回避のため一旦エスケープ
ReplaceComplexCreationWithFactoryMethodCheck:
  ignored_files:
    - "app/controllers/partners/reports_controller.rb"
ReplaceInstanceVariableWithLocalVariableCheck: { }
RestrictAutoGeneratedRoutesCheck: { }
SimplifyRenderInControllersCheck: { }
SimplifyRenderInViewsCheck: { }
#UseBeforeFilterCheck: { customize_count: 2 }
UseModelAssociationCheck: { }
UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
#UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { }
# NOTE: best_practicesの指示通りやるとデグレ起きるので一旦エスケープ
UseQueryAttributeCheck:
  ignored_files:
    - "app/admin/orders.rb"
    - "app/controllers/customers/orders_controller.rb"
    - "lib/tasks/update_held_order.rake"
UseSayWithTimeInMigrationsCheck: { }
UseScopeAccessCheck: { }
UseTurboSprocketsRails3Check: { }
